apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jellyfish-ui
  namespace: jellyfish
spec:
  selector:
    matchLabels:
      app: jellyfish-ui
  replicas: 3
  template:
    metadata:
      labels:
        app: jellyfish-ui
    spec:
      containers:
      - image: {{{jellyfish-ui-image}}}
        name: jellyfish-ui
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 4
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NGINX_PORT
          value: '80'
        - name: NODE_ENV
          value: {{{NODE_ENV}}}
        ports:
        - containerPort: 80
          name: jellyfish-ui
      imagePullSecrets:
        - name: com.docker.hub.travisciresin
