apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: tick-server
  namespace: jellyfish
spec:
  selector:
    matchLabels:
      app: tick-server
  template:
    metadata:
      labels:
        app: tick-server
    spec:
      containers:
      - image: {{{jellyfish-tick-server-image}}}
        name: tick-server
        lifecycle:
          preStop:
            exec:
              command: [ 'node', 'scripts/production/lock.js', '/tmp/worker.lock' ]
        env:
        - name: DATABASE
          value: postgres
        - name: POSTGRES_DATABASE
          value: {{POSTGRES_DATABASE}}
        - name: POSTGRES_USER
          value: {{POSTGRES_USER}}
        - name: POSTGRES_PASSWORD
          value: {{POSTGRES_PASSWORD}}
        - name: POSTGRES_PORT
          value: '{{POSTGRES_PORT}}'
        - name: POSTGRES_HOST
          value: {{POSTGRES_HOST}}
        - name: REDIS_HOST
          value: {{REDIS_HOST}}
        - name: REDIS_PASSWORD
          value: {{{REDIS_PASSWORD}}}
        - name: NODE_ENV
          value: {{{NODE_ENV}}}
        - name: SENTRY_DSN_SERVER
          value: {{{SENTRY_DSN_SERVER}}}
        - name: LOGENTRIES_TOKEN
          value: {{{LOGENTRIES_TOKEN}}}
        - name: LOGLEVEL
          value: {{{LOGLEVEL}}}
        - name: LOCKFILE
          value: /tmp/worker.lock
        - name: INTEGRATION_BALENA_API_PRIVATE_KEY
          value: {{{INTEGRATION_BALENA_API_PRIVATE_KEY}}}
        - name: INTEGRATION_BALENA_API_PUBLIC_KEY
          value: {{{INTEGRATION_BALENA_API_PUBLIC_KEY}}}
        - name: INTEGRATION_INTERCOM_TOKEN
          value: {{{INTEGRATION_INTERCOM_TOKEN}}}
        - name: INTEGRATION_FRONT_TOKEN
          value: {{{INTEGRATION_FRONT_TOKEN}}}
        - name: INTEGRATION_GITHUB_TOKEN
          value: {{{INTEGRATION_GITHUB_TOKEN}}}
        - name: INTEGRATION_GITHUB_SIGNATURE_KEY
          value: {{{INTEGRATION_GITHUB_SIGNATURE_KEY}}}
        - name: INTEGRATION_DISCOURSE_TOKEN
          value: {{{INTEGRATION_DISCOURSE_TOKEN}}}
        - name: INTEGRATION_DISCOURSE_USERNAME
          value: {{{INTEGRATION_DISCOURSE_USERNAME}}}
        - name: INTEGRATION_DISCOURSE_SIGNATURE_KEY
          value: {{{INTEGRATION_DISCOURSE_SIGNATURE_KEY}}}
        - name: INTEGRATION_OUTREACH_APP_ID
          value: {{{INTEGRATION_OUTREACH_APP_ID}}}
        - name: INTEGRATION_OUTREACH_APP_SECRET
          value: {{{INTEGRATION_OUTREACH_APP_SECRET}}}

      imagePullSecrets:
        - name: com.docker.hub.travisciresin
