---
apiVersion: v1
data:
  HTTP_WORKER_PORT: "8002"
  LOGLEVEL: "info"
  METRICS_PORT: "8888"
  NODE_ENV: "production"
  QUEUE_CONCURRENCY: "4"
  UV_THREADPOOL_SIZE: "128"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: jellyfish-action-server
  name: action-server
  namespace: '{{{KATAPULT_KUBE_NAMESPACE}}}'
