---
apiVersion: v1
data:
  NGINX_PORT: "80"
  NODE_ENV: "production"
  OAUTH_REDIRECT_BASE_URL: "https://jel.ly.fish"
  SENTRY_DSN_UI: "https://ff836b1e4abc4d0699bcaaf07ce4ea08@sentry.io/1366139"
  SERVER_HOST: "https://api.ly.fish"
  SERVER_PORT: "443"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: jellyfish-ui
    app.kubernetes.io/name: jellyfish-ui
  name: jellyfish-ui
  namespace: '{{{KATAPULT_KUBE_NAMESPACE}}}'
