apiVersion: v1
kind: Service
metadata:
  labels:
    name: jellyfish-ui
  namespace: {{{KATAPULT_KUBE_NAMESPACE}}}
  name: jellyfish-ui
spec:
  selector:
    app: jellyfish-ui
  ports:
  - port: 80
    name: jellyfish-ui
